; Drush Make API version
api = 2

; Core version
core = 7.x

projects[drupal][version] = 7.x

; Modules
projects[views][type] = "module"
projects[views][subdir] = "contrib"
projects[ctools][type] = "module"
projects[ctools][subdir] = "contrib"
projects[entity][type] = "module"
projects[entity][subdir] = "contrib"
projects[backup_migrate][type] = "module"
projects[backup_migrate][subdir] = "contrib"
projects[ds][type] = "module"
projects[ds][subdir] = "contrib"
projects[libraries][type] = "module"
projects[libraries][subdir] = "contrib"
projects[devel][type] = "module"
projects[devel][subdir] = "contrib"
projects[rules][type] = "module"
projects[rules][subdir] = "contrib"
projects[admin_menu][type] = "module"
projects[admin_menu][subdir] = "contrib"
projects[globalredirect][subdir] = "contrib"
projects[globalredirect][type] = "module"
projects[pathauto][type] = "module"
projects[pathauto][subdir] = "contrib"
projects[link][type] = "module"
projects[link][subdir] = "contrib"
projects[jquery_update][type] = "module"
projects[jquery_update][subdir] = "contrib"
projects[token][type] = "module"
projects[token][subdir] = "contrib"
projects[admin_menu][type] = "module"
projects[admin_menu][subdir] = "contrib"
projects[menu_block][type] = "module"
projects[menu_block][subdir] = "contrib"
projects[context][type] = "module"
projects[context][subdir] = "contrib"
projects[context_omega][type] = "module"
projects[context_omega][subdir] = "contrib"
projects[webform][type] = "module"
projects[webform][subdir] = "contrib"
projects[module_filter][type] = "module"
projects[module_filter][subdir] = "contrib"
projects[shield][type] = "module"
projects[shield][subdir] = "contrib"
;projects[less][type] = "module"
;projects[less][subdir] = "contrib"
projects[date][type] = "module"
projects[date][subdir] = "contrib"
projects[media][type] = "module"
projects[media][subdir] = "contrib"
projects[media_youtube][type] = "module"
projects[media_youtube][subdir] = "contrib"
projects[l10n_update][type] = "module"
projects[l10n_update][subdir] = "contrib"
projects[i18n][type] = "module"
projects[i18n][subdir] = "contrib"
projects[menu_block][type] = "module"
projects[menu_block][subdir] = "contrib"
projects[delta][type] = "module"
projects[delta][subdir] = "contrib"
projects[wysiwyg][type] = "module"
projects[wysiwyg][subdir] = "contrib"
projects[email][type] = "module"
projects[email][subdir] = "contrib"
projects[link][type] = "module"
projects[link][subdir] = "contrib"
projects[references][type] = "module"
projects[references][subdir] = "contrib"
projects[nodequeue][type] = "module"
projects[nodequeue][subdir] = "contrib"
projects[empty_page][type] = "module"
projects[empty_page][subdir] = "contrib"
projects[update_advanced][type] = "module"
projects[update_advanced][subdir] = "contrib"
projects[variable][type] = "module"
projects[variable][subdir] = "contrib"

; Libraries
;libraries[ckeditor][download][type] = "get"
;libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor/CKEditor/CKEditor%203.6.4/ckeditor_3.6.4.tar.gz"
;libraries[ckeditor][directory_name] = "ckeditor"
;libraries[ckeditor][type] = "library"

libraries[lessphp][download][type] = "get"
libraries[lessphp][download][url] = "http://leafo.net/lessphp/src/lessphp-0.4.0.tar.gz"
libraries[lessphp][directory_name] = "lessphp"
libraries[lessphp][type] = "library"

; Themes
; ------
projects[] = omega 
